"""Where the test data lives, and what each part of it is.

Kept out of `conftest.py` so test modules can import these plainly. Every path
is derived from `__file__`, so the suite passes from any working directory.
"""

import zlib
from pathlib import Path

TESTS = Path(__file__).absolute().parent
PROJECT_ROOT = TESTS.parent
DATA = TESTS / "data"
DEMOS = TESTS / "demos"

#: The layouts bundled with TouchOSC 1.5.2, saved out of the application. These
#: are Hexler's own polished designs -- pagers, scripts, grids, sensors, gamepad
#: bindings -- and are the highest-authority evidence available for what the
#: format actually contains.
EXAMPLES = TESTS / "examples"

#: Saved and exported from TouchOSC 1.5.2.262: a group holding a fader and a
#: label. The two files are the same document in the two formats the editor
#: writes, which makes them the reference for round-trip fidelity.
SAMPLE_TOSC = DATA / "fader_with_label.tosc"
SAMPLE_XML = DATA / "fader_with_label.xml"

#: Every layout in the corpus, in both formats.
CORPUS = sorted(
    p
    for directory in (DATA, EXAMPLES)
    if directory.is_dir()
    for p in directory.iterdir()
    if p.suffix.lower() in (".tosc", ".xml")
)


def payload(path: Path) -> bytes:
    """The XML of a corpus file, decompressed if it needs to be."""
    raw = path.read_bytes()
    return zlib.decompress(raw) if path.suffix.lower() == ".tosc" else raw


#: The corpus files TouchOSC itself wrote, identified by the XML declaration.
#: The rest were generated by tosclib 0.3.x, which emitted no declaration and
#: double-quoted its attributes because it serialized through ElementTree.
#: Those are still valid input, but they are not a fidelity reference:
#: reproducing them byte for byte would mean reproducing the old library's
#: quirks rather than the editor's.
EDITOR_WRITTEN = [p for p in CORPUS if payload(p).startswith(b"<?xml")]
