"""Does the API cover what the format actually contains?

The tests elsewhere check that what py2tosc reads it can write back. These check
something different and weaker-but-broader: that the *vocabulary* the library
ships -- property type table, per-type defaults, enum spellings, element tags --
agrees with what TouchOSC itself puts in files.

Expectations are derived from `tests/data` rather than written out by hand, so
adding a layout to the corpus extends the checks automatically, and a wrong
guess in the library fails here rather than in someone's editor.

Only files the editor wrote are treated as authoritative. The rest of the corpus
was generated by tosclib 0.3.x and reflects that library's mistakes.
"""

import xml.etree.ElementTree as ET
from collections import defaultdict

import pytest

import py2tosc
from _corpus import EDITOR_WRITTEN, payload
from py2tosc.defaults import default_values_for, defaults_for
from py2tosc.enums import ControlType
from py2tosc.properties import KNOWN_TYPES

#: TouchOSC omits these when they are empty, and py2tosc leaves them to the
#: caller rather than inventing a name. See `defaults.py`.
CALLER_SUPPLIED = {"name", "tag", "script"}

#: Elements that exist only in lexml 6, so writing a version 3 document
#: legitimately drops them. This is about *elements*, not properties: since a
#: 1.5.2 layout covering all thirteen control types joined the corpus, no
#: property needs excusing any more.
VERSION_6_ELEMENTS = {"includes", "noDuplicates"}


def parsed():
    """Every editor-written layout, as (path, root element, version)."""
    for path in EDITOR_WRITTEN:
        root = ET.fromstring(payload(path))
        yield path, root, root.get("version", "6")


def nodes_by_type():
    """camelCase control type -> list of `<node>` elements the editor wrote."""
    found = defaultdict(list)
    for _, root, _ in parsed():
        for node in root.iter("node"):
            found[node.get("type")].append(node)
    return found


NODES = nodes_by_type()
TYPES_WITH_SAMPLES = [t for t in ControlType if NODES.get(t.value)]


def test_the_corpus_covers_every_control_type():
    """If this fails, the checks below silently stop covering something."""
    assert len(TYPES_WITH_SAMPLES) == len(list(ControlType))


# -- property types ---------------------------------------------------------


def test_known_types_agrees_with_the_format():
    """Every property key's type in our table must match what the editor writes.

    This is the table that decides how `control.some_key = value` is stored. A
    wrong entry writes a well-formed file with the wrong property type in it,
    which no round-trip test would catch.
    """
    observed = defaultdict(set)
    for _, root, _ in parsed():
        for prop in root.iter("property"):
            key = prop.findtext("key")
            if key:
                observed[key].add(prop.get("type"))

    conflicts = [
        (key, KNOWN_TYPES[key].value, sorted(types))
        for key, types in observed.items()
        if key in KNOWN_TYPES and KNOWN_TYPES[key].value not in types
    ]
    assert not conflicts, f"KNOWN_TYPES disagrees with the format: {conflicts}"


def test_every_composite_property_key_is_in_the_table():
    """Colour and frame keys must be listed, because both are 4-tuples.

    For any other type the Python value is enough to infer from. For these two
    it is not: without a table entry, `control.some_colour = (255, 0, 0, 255)`
    would be stored as a frame.
    """
    composite = defaultdict(set)
    for path, root, _ in parsed():
        for prop in root.iter("property"):
            key = prop.findtext("key")
            if key and prop.get("type") in ("c", "r"):
                composite[key].add(path.name)

    # style1 is a user-defined property from the custom-property demo, not part
    # of the format. Custom composite keys are the caller's to declare; see
    # test_a_custom_colour_key_needs_an_explicit_type.
    missing = sorted(set(composite) - set(KNOWN_TYPES) - {"style1"})
    assert not missing, f"composite keys absent from KNOWN_TYPES: {missing}"


def test_a_custom_colour_key_needs_an_explicit_type():
    """The documented way round the ambiguity above."""
    control = py2tosc.group()

    # A bare 4-tuple of ints is read as a frame, which is the safe default.
    control.set("myTint", (255, 0, 0, 255))
    assert control.properties["myTint"].type is py2tosc.PropertyType.FRAME

    # Both of these say "colour" unambiguously.
    control.set("myTint", py2tosc.to_color((255, 0, 0, 255)))
    assert control.properties["myTint"].type is py2tosc.PropertyType.COLOR

    control.set("myOtherTint", (255, 0, 0, 255), type="c")
    assert control.properties["myOtherTint"].type is py2tosc.PropertyType.COLOR


# -- per-control-type defaults ----------------------------------------------


@pytest.mark.parametrize("control_type", TYPES_WITH_SAMPLES, ids=lambda t: t.value)
def test_defaults_cover_every_property_the_editor_writes(control_type):
    """Our defaults must not omit a property the editor puts on every instance.

    Extra properties are tolerated -- TouchOSC accepts keys it does not know --
    so this checks one direction only.
    """
    per_node = [
        {p.findtext("key") for p in properties}
        for node in NODES[control_type.value]
        if (properties := node.find("properties")) is not None
    ]
    on_every_one = set.intersection(*per_node) if per_node else set()

    ours = set(defaults_for(control_type))
    missing = sorted(on_every_one - ours - CALLER_SUPPLIED)

    assert not missing, (
        f"{control_type.value} defaults omit {missing}, which the editor writes "
        f"on all {len(per_node)} instances in the corpus"
    )


@pytest.mark.parametrize("control_type", TYPES_WITH_SAMPLES, ids=lambda t: t.value)
def test_default_value_keys_match_the_format(control_type):
    """A control's values are fixed by its type, so these must match exactly.

    Order is not checked: the editor writes `touch` first in lexml 3 files and
    last in lexml 6 ones, so it plainly does not matter.
    """
    observed = {
        frozenset(v.findtext("key") for v in values)
        for node in NODES[control_type.value]
        if (values := node.find("values")) is not None
    }
    observed.discard(frozenset())
    if not observed:
        pytest.skip(f"no {control_type.value} in the corpus carries values")

    ours = frozenset(key for key, _ in default_values_for(control_type))
    assert ours in observed, (
        f"{control_type.value} values are {sorted(ours)}, "
        f"the editor writes {[sorted(o) for o in observed]}"
    )


# -- enumerations -----------------------------------------------------------


def collect(finder):
    seen = set()
    for _, root, _ in parsed():
        seen |= {v for v in finder(root) if v}
    return seen


@pytest.mark.parametrize(
    "enum, finder",
    [
        (py2tosc.ControlType, lambda r: (n.get("type") for n in r.iter("node"))),
        (py2tosc.PropertyType, lambda r: (p.get("type") for p in r.iter("property"))),
        (py2tosc.PartialType, lambda r: (p.findtext("type") for p in r.iter("partial"))),
        (py2tosc.Conversion, lambda r: (p.findtext("conversion") for p in r.iter("partial"))),
        (py2tosc.TriggerCondition, lambda r: (t.findtext("condition") for t in r.iter("trigger"))),
        (py2tosc.MidiType, lambda r: (m.findtext("message/type") for m in r.iter("midi"))),
    ],
    ids=lambda x: getattr(x, "__name__", ""),
)
def test_enum_spellings_match_the_format(enum, finder):
    """Every value the editor writes must be a member of the matching enum.

    This is what catches a guessed spelling. `MidiType.NOTE_ON` shipped as
    `NOTEON` until the corpus showed the format writes `NOTE_ON`.
    """
    observed = collect(finder)
    ours = {member.value for member in enum}
    unknown = sorted(observed - ours)
    assert not unknown, f"{enum.__name__} has no member for {unknown}"


# -- elements ---------------------------------------------------------------


def test_every_element_in_the_format_survives_a_round_trip():
    """No element tag the editor writes may be dropped on the way through.

    Coverage in the round-trip sense: parse each layout, write it back, and
    compare the set of tags. A tag the model has no home for would vanish here.
    """
    for path, root, _ in parsed():
        before = {el.tag for el in root.iter()}
        after = {el.tag for el in ET.fromstring(py2tosc.load(path).dumps()).iter()}

        lost = sorted(before - after)
        # <includes> and <noDuplicates> are version 6 elements and are not
        # written into a version 3 document; nothing else may go missing.
        assert not set(lost) - VERSION_6_ELEMENTS, f"{path.name} lost {lost}"


def test_message_fields_are_fully_modelled():
    """Every child of a message element must map to a field on our dataclass."""
    dataclasses = {
        "osc": py2tosc.OscMessage,
        "midi": py2tosc.MidiMessage,
        "local": py2tosc.LocalMessage,
        "gamepad": py2tosc.GamepadMessage,
    }
    observed = defaultdict(set)
    for _, root, _ in parsed():
        for messages in root.iter("messages"):
            for message in messages:
                observed[message.tag] |= {child.tag for child in message}

    assert set(observed) <= set(dataclasses), f"unmodelled message: {set(observed) - set(dataclasses)}"

    for tag, fields in observed.items():
        ours = {
            "".join(w.title() if i else w for i, w in enumerate(f.split("_")))
            for f in dataclasses[tag].__dataclass_fields__
        }
        # dstID is the one field whose file spelling is not plain camelCase.
        ours |= {"dstID"} if tag == "local" else set()
        missing = sorted(fields - ours)
        assert not missing, f"<{tag}> fields not modelled: {missing}"


def test_value_keys_are_all_reachable():
    """Every value key in the format can be found via `Control.value`."""
    observed = collect(lambda r: (v.findtext("key") for v in r.iter("values") for v in v))
    control = py2tosc.Control("XY", values=[py2tosc.Value(key=k) for k in sorted(observed)])
    for key in observed:
        assert control.value(key) is not None, key
